"""
Full ML pipeline: ties together detection, OCR (with multi-frame voting),
and accident detection into unified event dicts ready to push to Kafka/Supabase.

This is what the backend teammate imports and calls -- they don't need to
know anything about YOLO/OCR internals, just call `process_camera_pass(...)`
or `process_frame_for_anomaly(...)` and get back clean event dicts matching
the shared schema.

Event schema (matches the Supabase `detections` table):
    {
        "plate": str | None,
        "camera_id": str,
        "lat": float,
        "lon": float,
        "timestamp": int,
        "confidence": float,
        "event_type": "plate_detection"
    }

Event schema (matches the Supabase `alerts` table):
    {
        "event_type": "accident_alert" | "blacklist_alert",
        "anomaly_type": str | None,
        "camera_id": str,
        "timestamp": int,
        "confidence": float
    }
"""
from ocr_engine import read_plate_multiframe
from accident_detection import AnomalyDetector

# in production this comes from a camera registry table (Supabase), keyed by camera_id
CAMERA_LOCATIONS = {
    "CAM-01": (26.7606, 83.3732),
    "CAM-02": (26.7550, 83.3900),
    "CAM-03": (26.7480, 83.4100),
    "CAM-04": (26.7700, 83.4250),
    "CAM-05": (26.7820, 83.4050),
}

BLACKLIST = {"KA05MZ4444"}  # stand-in for a real blacklist table lookup

_anomaly_detectors = {}  # one stateful detector instance per camera


def process_camera_pass(frame_crops, camera_id, timestamp):
    """
    Call this once per 'pass' of a vehicle through a camera (i.e. once you
    have ~3 consecutive plate crops from the detection stage for one vehicle).
    Returns a plate_detection event, and a blacklist_alert event if matched.
    """
    result = read_plate_multiframe(frame_crops)
    lat, lon = CAMERA_LOCATIONS.get(camera_id, (None, None))

    detection_event = {
        "event_type": "plate_detection",
        "plate": result["plate"],
        "camera_id": camera_id,
        "lat": lat,
        "lon": lon,
        "timestamp": timestamp,
        "confidence": result["confidence"],
        "frames_used": result["frames_used"],
    }

    alert_event = None
    if result["plate"] in BLACKLIST:
        alert_event = {
            "event_type": "blacklist_alert",
            "plate": result["plate"],
            "camera_id": camera_id,
            "lat": lat, "lon": lon,
            "timestamp": timestamp,
            "confidence": result["confidence"],
        }

    return detection_event, alert_event


def process_frame_for_anomaly(frame_bgr, camera_id, timestamp):
    """Call this per raw video frame (independent of the OCR pass) to check for accidents/stalls."""
    if camera_id not in _anomaly_detectors:
        _anomaly_detectors[camera_id] = AnomalyDetector()
    return _anomaly_detectors[camera_id].process_frame(frame_bgr, camera_id, timestamp)


if __name__ == "__main__":
    # demo run against the synthetic dataset generated by 1_generate_plates.py
    import cv2, json

    manifest = json.load(open("/home/claude/plates/manifest.json"))
    by_pass = {}
    for m in manifest:
        key = (m["true_plate"], m["camera_id"], m["t_offset"])
        by_pass.setdefault(key, []).append(m["file"])

    print("=== Plate detection events ===")
    all_events = []
    for (true_plate, cam, t), files in sorted(by_pass.items(), key=lambda kv: kv[0][2]):
        crops = [cv2.imread(f"/home/claude/plates/{f}") for f in files]
        detection, alert = process_camera_pass(crops, cam, t)
        all_events.append(detection)
        print(f"  {detection}")
        if alert:
            print(f"  !! BLACKLIST ALERT: {alert}")
            all_events.append(alert)

    with open("/home/claude/plates/events_output.json", "w") as f:
        json.dump(all_events, f, indent=2)
    print(f"\nWrote {len(all_events)} events to plates/events_output.json")
